version: '2.4'

services:
  elasticsearch:
#    env_file: environment.env
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - /mnt/cache/appdata/docker-elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      br0:
        ipv4_address: 10.20.30.171
      default: {}
    restart: unless-stopped

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - /mnt/cache/appdata/docker-elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - /mnt/cache/appdata/docker-elk/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    networks:
      br0:
        ipv4_address: 10.20.30.172
      default: {}
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - /mnt/cache/appdata/docker-elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - /mnt/cache/appdata/wazuh/kibana/wazuh.yml:/usr/share/kibana/optimize/wazuh/config/wazuh.yml:rw
    ports:
      - "5601:5601"
    environment:
      NODE_OPTIONS: "--max-old-space-size=4096"
    networks:
      br0:
        ipv4_address: 10.20.30.170
      default: {}
    depends_on:
      - elasticsearch
    restart: unless-stopped

networks:
  br0:
    external: true

volumes:
  elasticsearch:
